collections_config:
  contact:
    disable_add: true
    icon: contact_page
  company:
    disable_add: true
  interior-design-portfolio:
    disable_add: true
  luxury-staging:
    disable_add: true
  showroom:
    disable_add: true
  team:
    disable_add: true
    icon: person_add
  thank-you:
    disable_add: true
    icon: mark_email_read
collection_groups:
  - heading: Profile and Settings
    collections:
      - data
  - heading: Pages
    collections:
      - company
      - contact
      - interior-design-portfolio
      - luxury-staging
      - shop
      - showroom
      - team
      - thank-you
      - pages
_inputs:
  gallery:
    type: array
  photos:
    type: image
  furniture:
    label: category
    type: select
    options:
      values:
        - Bedroom
        - Decor
        - Outdoor
        - Office
        - Living Room
        - Dining Room