baseURL = "https://www.ambiancehome.com/"
enableRobotsTXT = "true"
languageCode = "en-us"
[[menu.main]]
name = "Contact"
parent = "About Us"
url = "/contact"
weight = 3
[[menu.main]]
name = "Projects"
parent = "Luxury Staging"
weight = 1
url = "/luxury-staging"
[[menu.main]]
name = "Portfolio"
parent = "Interior Design"
url = "/interior-design-portfolio/"
weight = 1
[[menu.main]]
name = "About"
parent = "About Us"
url = "/company"
weight = 1
[[menu.main]]
name = "Shop"
url = "/shop"
weight = 6
[[menu.main]]
name = "Showroom"
url = "/showroom"
weight = 5
[[menu.main]]
name = "Luxury Staging"
weight = 4
[[menu.main]]
name = "Interior Design"
weight = 3
[[menu.main]]
name = "About Us"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[taxonomies]
category = "categories"
tag = "tags"
furniture = "furnitures"
